package com.videojuegoshop.enitity;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

// Generated 1 abr 2022 13:11:07 by Hibernate Tools 5.6.3.Final

/**
 * DetallesPedido generated by hbm2java
 */

@Entity
@Table(name = "detalles_pedido", catalog = "videogameshopyaa")
@NamedQueries({
	@NamedQuery(name = "DetallePedidos.bestSelling", 
			query = "SELECT dp.videojuego FROM DetallesPedido dp GROUP by dp.videojuego.videojuegoId "
					+ "ORDER BY SUM(dp.cantidad) DESC")
})
public class DetallesPedido implements java.io.Serializable {

	private DetallesPedidoId id = new DetallesPedidoId();
	private Videojuego videojuego;
	private VideojuegoPedido videojuegoPedido;
	private int cantidad;
	private float subtotal;

	public DetallesPedido() {
	}

	public DetallesPedido(DetallesPedidoId id) {
		this.id = id;
	}

	public DetallesPedido(DetallesPedidoId id, Videojuego videojuego, VideojuegoPedido videojuegoPedido, int cantidad,
			float subtotal) {
		this.id = id;
		this.videojuego = videojuego;
		this.videojuegoPedido = videojuegoPedido;
		this.cantidad = cantidad;
		this.subtotal = subtotal;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "pedido_id", column = @Column(name = "pedido_id", nullable = false)),
			@AttributeOverride(name = "videojuego_id", column = @Column(name = "videojuego_id", nullable = false)) })
	public DetallesPedidoId getId() {
		return this.id;
	}

	public void setId(DetallesPedidoId id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "videojuego_id", insertable = false, updatable = false, nullable = false)
	public Videojuego getVideojuego() {
		return this.videojuego;
	}

	public void setVideojuego(Videojuego videojuego) {
		this.videojuego = videojuego;
		this.id.setVideojuego(videojuego);
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pedido_id", insertable = false, updatable = false, nullable = false)
	public VideojuegoPedido getVideojuegoPedido() {
		return this.videojuegoPedido;
	}

	public void setVideojuegoPedido(VideojuegoPedido videojuegoPedido) {
		this.videojuegoPedido = videojuegoPedido;
		this.id.setVideojuegoPedido(videojuegoPedido);
	}
	
	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}
	@Column(name = "subtotal", nullable = false, precision = 12, scale = 0)
	public float getSubtotal() {
		return subtotal;
	}

	public void setSubtotal(float subtotal) {
		this.subtotal = subtotal;
	}

}