package com.videojuegoshop.enitity;

import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

// Generated 1 abr 2022 13:11:07 by Hibernate Tools 5.6.3.Final

/**
 * DetallesPedidoId generated by hbm2java
 */
@Embeddable
public class DetallesPedidoId implements java.io.Serializable {

	private Videojuego videojuego;
	private VideojuegoPedido videojuegoPedido;

	
	public DetallesPedidoId() {
	}
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "videojuego_id", insertable = false, updatable = false, nullable = false)
	public Videojuego getVideojuego() {
		return this.videojuego;
	}

	public void setVideojuego(Videojuego videojuego) {
		this.videojuego = videojuego;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pedido_id", insertable = false, updatable = false, nullable = false)
	public VideojuegoPedido getVideojuegoPedido() {
		return this.videojuegoPedido;
	}

	public void setVideojuegoPedido(VideojuegoPedido videojuegoPedido) {
		this.videojuegoPedido = videojuegoPedido;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((videojuego == null) ? 0 : videojuego.hashCode());
		result = prime * result + ((videojuegoPedido == null) ? 0 : videojuegoPedido.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DetallesPedidoId other = (DetallesPedidoId) obj;
		if (videojuego == null) {
			if (other.videojuego != null)
				return false;
		} else if (!videojuego.equals(other.videojuego))
			return false;
		if (videojuegoPedido == null) {
			if (other.videojuegoPedido != null)
				return false;
		} else if (!videojuegoPedido.equals(other.videojuegoPedido))
			return false;
		return true;
	}

}